spring:
  application:
    name: cookie-monsters
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  http:
    client:
      enabled: false
      #base-url: http://107.21.167.30:8081
      #base-url: http://localhost:8080
      connection-timeout: 5000
      read-timeout: 10000

  microservices:
    grayscale-url: http://localhost:5296/grayscale

  storage:
    s3:
      enabled: false # saves locally
    local:
      dir: uploads/
      base-url: http://localhost:8080/uploads/

logging:
  file:
    name: logs/cookie-monsters.log
  level:
    root: INFO
    com.app: TRACE