server:
  port: 8080

spring:
  datasource:
    url: "${SPRING_DATASOURCE_URL}"
    username: "${SPRING_DATASOURCE_USERNAME}"
    password: "${SPRING_DATASOURCE_PASSWORD}"
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  microservices:
    # reads variable from docker-compose.yml
    image-filtering-url: ${APP_MICROSERVICES_IMAGEFILTERING_URL:http://image-filtering-service:8080/filter}

  storage:
    s3:
      enabled: true # uploads on Amazon S3
      bucket-name: cookie-monsters-images