name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: 1. Compile the project and prepare files
        run: |
          mvn clean package -DskipTests
          mv target/*.jar target/app.jar
          cp Dockerfile docker-compose.yml target/
          
          # Replicate C# directory tree structure inside target/ for transfer
          mkdir -p target/src/microservices
          cp -r src/microservices/ImageFilteringMicroservice target/src/microservices/

      - name: 2. Transfer the .jar, Dockerfiles and microservices to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PEM_KEY }}
          source: "target/app.jar,target/Dockerfile,target/docker-compose.yml,target/src"
          target: "/home/ubuntu/app"
          strip_components: 1

      - name: 3. SSH into EC2, Rebuild and Run Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PEM_KEY }}
          script: |
            cd /home/ubuntu/app
            
            # Create the .env file dynamically from GitHub Secrets
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" > .env
            
            # Stop and remove existing containers
            sudo docker compose down
            
            # Clean up old images, stopped containers, and build cache to free up space
            sudo docker system prune -a -f
            
            # Rebuild the images and start the containers
            sudo docker compose up -d --build